// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Get basic frame info from raw RGBA bytes
FrameInfo getFrameInfo(
        {required List<int> bytes, required int width, required int height}) =>
    Native.instance.api.crateFrameProcessorGetFrameInfo(
        bytes: bytes, width: width, height: height);

/// Process frame — applies pipeline: resize if 4K → normalize → return
ProcessedFrame processFrame(
        {required List<int> bytes, required int width, required int height}) =>
    Native.instance.api.crateFrameProcessorProcessFrame(
        bytes: bytes, width: width, height: height);

/// Convert frame to grayscale
ProcessedFrame applyGrayscale(
        {required List<int> bytes, required int width, required int height}) =>
    Native.instance.api.crateFrameProcessorApplyGrayscale(
        bytes: bytes, width: width, height: height);

/// Adjust brightness (-255 to +255)
ProcessedFrame applyBrightness(
        {required List<int> bytes,
        required int width,
        required int height,
        required int value}) =>
    Native.instance.api.crateFrameProcessorApplyBrightness(
        bytes: bytes, width: width, height: height, value: value);

/// Metadata about a frame
class FrameInfo {
  final int width;
  final int height;
  final BigInt sizeBytes;

  const FrameInfo({
    required this.width,
    required this.height,
    required this.sizeBytes,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ sizeBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrameInfo &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          sizeBytes == other.sizeBytes;
}

/// Result of frame processing
class ProcessedFrame {
  final Uint8List data;
  final int width;
  final int height;

  const ProcessedFrame({
    required this.data,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode => data.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcessedFrame &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          width == other.width &&
          height == other.height;
}
